#!/bin/bash
set -e

eval `env -i envdir ./env env`

NUM=${NUM:-0}
WALDIR=${WALDIR:-/srv/mersenne/wal}
SNAPDIR=${SNAPDIR:-/srv/mersenne/snap}

mkdir -p $WALDIR $SNAPDIR
chown -R mersenne $WALDIR $SNAPDIR

exec 2>&1
exec envuidgid mersenne envdir ./env /usr/bin/mersenne \
	-p $NUM                                        \
	--acceptor-wal-dir $WALDIR                     \
	--acceptor-snap-dir $SNAPDIR
