#!/bin/bash
set -e

eval `env -i envdir ./env env`

NUM=${NUM:-0}
WALDIR=${WALDIR:-/var/lib/mersenne}

mkdir -p $WALDIR$NUM/{wal,snap}
chown -R mersenne $WALDIR$NUM

exec 2>&1
exec envuidgid mersenne envdir ./env /usr/bin/mersenne \
	-p $NUM                                        \
	--acceptor-wal-dir $WALDIR$NUM/wal             \
	--acceptor-snap-dir $WALDIR$NUM/snap
